name: js_tests

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Cambiar a carpeta correcta
        run: cd Juego-piedra-papel-o-tijera

      - name: Install dependencies
        run: npm install
        working-directory: Juego-piedra-papel-o-tijera

      - name: Run tests
        run: npm test
        working-directory: Juego-piedra-papel-o-tijera

      - name: Run tests
        run: npm test
